version: "3.7"
services:
  bestiary-dnd:
    build:
      context: .
    container_name: bestiary-dnd
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    env_file:
      .env
    networks:
      - mynetwork

  postgres_db:
    image: "postgres:15"
    container_name: bestiary-dnd-db
    restart: always
    networks:
      - mynetwork
    env_file:
      .env

networks:
  mynetwork:
    driver: bridge
