version: "3.7"
services:
  bestiary-dnd:
    build:
      context: .
    container_name: bestiary-dnd
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    env_file:
      .env
  postgres_db:
    image: "postgres:15"
    container_name: bestiary-dnd-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      .env