spring:
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
  cloud:
    vault:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/bestiary-dnd-db
    username: admin
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: none
    show-sql: true
